name: Grocery
data_root: ./Data

text_path: ./Data/Grocery/Grocery.csv
image_path: ./Data/Grocery/GroceryImages
graph_path: ./Data/Grocery/GroceryGraph.pt
v_emb_path: ./Data/Grocery/ImageFeatures/Grocery_image_clip_vit_large_patch14_768d.npy
t_emb_path: ./Data/Grocery/TextFeatures/Grocery_text_clip_vit_large_patch14_768d.npy
train_ratio: 0.6
val_ratio: 0.2
lp_val_ratio: 0.1
lp_test_ratio: 0.2
edge_split_path: None
num_neg: 1000