name: Toys
data_root: ./Data

text_path: ./Data/Toys/Toys.csv
image_path: ./Data/Toys/ToysImages
graph_path: ./Data/Toys/ToysGraph.pt
v_emb_path: ./Data/Toys/ImageFeatures/Toys_image_clip_vit_large_patch14_768d.npy
t_emb_path: ./Data/Toys/TextFeatures/Toys_text_clip_vit_large_patch14_768d.npy
train_ratio: 0.6
val_ratio: 0.2
lp_val_ratio: 0.2
lp_test_ratio: 0.2
edge_split_path: None
num_neg: 5000